### ISSUE TITLE
What is the status of this project?

### ISSUE THREAD

**Issue by dashohoxha** [turicas/easygpg#1]
Is it working?
How to install it?
How does it work? How is it different from simple `gpg`?
What is the aim or goal of the project?
Why Python and not, for example, bash?

**Comment by turicas** [comment]
Hello, @dashohoxha, thanks for creating this issue. I'm going to answer all questions and then close it, ok?

**Question**: _Is it working?_
**Answer**: Yes! It works for some `gpg` commands (the most used by me and some of my friends).

**Question**: _How to install it?_
**Answer**: By now you need to get the entire repository (`git clone https://github.com/turicas/easygpg.git`) and then install using `setup.py` (by running `cd easygpg; python setup.py install` -- if you're not inside a [virtualenv](https://pypi.python.org/pypi/virtualenv) you must be root to run this `setup.py` command). In a future (when it become a little stable) it will be available as in [Python Package Index](http://pypi.python.org/) (so you just need to run `pip install easygpg`) and also on major GNU/Linux distributions, such as Debian and Ubuntu.

**Question**: _How does it work? How is it difference from simple `gpg`?_
**Answer**: This is just a wrapper around the `gpg` command-line tool: you type `easygpg some-command` and it will translate into some `gpg` command.

**Question**: _What is the aim or goal of the project?_
**Answer**: The reason it was created is because `gpg` is counter-intuitive and have some ambiguous/inconsistent-named options. The ideia is to keep GPG command-line usage simple and intuitive (after installing type `easygpg --help` or `egpg --help` to see the available commands). Keep in mind it's a proof-of-concept yet.

**Question**: _Why Python and not, for example, bash?_
**Answer**: Because I know more Python than bash and find it way easier and quicker to create usable command-line interfaces. Python is included by default in almost all GNU/Linux distributions and on Mac OS X (and also support Windows). We can migrate to another language/platform in the future if it is proved to be the best thing to do (and we may automate the process using Python itself), but I don't see it happening now.

If you find one of these answers should be on our [README](https://github.com/turicas/easygpg/blob/develop/README.md) to clarify some things, please feel free to create a pull request with the changes. :)

**Comment by dashohoxha** [comment]
@turicas Thanks for taking the time to answer these questions. All the answers are the obvious ones, the ones that I expected. I don't remember why I asked, maybe just to ping (is it alive), or maybe because the README is just bare. I think that all the information that you have explained above should go to the README. You can even just copy/paste it as a Q&A section. I can also do it, if you would like me to get my hands dirty, I don't mind.

However the question `How does it work?` is not answered properly. I actually meant `How to use it, what are the commands, options, etc.`. I can also read the code and try to understand, but this is not normal, especially for a tool that pretends to be `easy...`.

Also, if you know of any other similar projects (which try to make gpg easy), you can list them on a section of similar projects (on README). I am interested on some easy gpg tool, but I couldn't find something quite appropriate yet.

Right now I am a bit busy with this project: https://github.com/dashohoxha/pw but once I finish it (hopefully soon), I am planing to work on some easy gpgp kind of project, maybe starting by forking this one: https://github.com/nyarly/simplekey . This project is in Bash and I am quite familiar with bash scripting (on the other hand, I have very basic knowledge of Python).

Would you be interested to help, even just with ideas or testing? I think that the ideas are the most difficult part, it is not so clear how to simplify GPG properly. Once they are clear, the implementation should not be very difficult.
